### ISSUE TITLE
Reinstate CI tests

### ISSUE THREAD

**Issue by thclark** [octue/twined-components#2]
### Use Case

Best practices dictate use of jest and coverage for CI of frontend code.

### Current state

Removed what frontend tests there were 

### Proposed solution

In addition to actually creating a bunch of frontend tests (e.g. using chromatic), we should reinstate them as actual CI process.

We'd begun with CI using the following GHA:

```
# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test-ci

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Chromatic needs the whole history to fetch the base build
      - name: Install modules
        run: yarn
      - name: Run tests with coverage
        run: yarn run coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          buildScriptName: storybook
          allowConsoleErrors: False
```
